/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Window;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Ever Chavez
 */
public class PanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        cargarTablaUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        scrollUsuarios = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnEntrar1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR USUARIO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 520, -1));

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel3.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 120, -1));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, -1));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 130, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre de Usuario");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        cmbRol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Tecnico" }));
        jPanel3.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        scrollUsuarios.setViewportView(tablaUsuarios);

        jPanel3.add(scrollUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 210));

        btnEntrar1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEntrar1.setText("Guardar");
        btnEntrar1.addActionListener(this::btnEntrar1ActionPerformed);
        jPanel3.add(btnEntrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 130, -1));

        btnModificar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 120, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTablaUsuarios() {
        javax.swing.table.DefaultTableModel modeloTabla = (javax.swing.table.DefaultTableModel) tablaUsuarios.getModel();
        modeloTabla.setRowCount(0); // Limpiamos la tabla antes de llenarla

        dao.UsuarioDAO daoUsuario = new dao.UsuarioDAO();
        java.util.List<modelo.Usuario> lista = daoUsuario.listarUsuarios();

        for (modelo.Usuario u : lista) {
            Object[] fila = new Object[3];
            fila[0] = u.getIdUsuario();
            fila[1] = u.getNombreUsuario();
            fila[2] = u.getRol();
            modeloTabla.addRow(fila);
        }
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        String usuario = txtUsuario.getText().trim();
        // Así se extrae el texto de un campo de contraseña de forma segura
        String password = new String(txtPassword.getPassword());

        // Validación rápida de campos vacíos
        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese usuario y contraseña.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Llamamos a nuestro conductor de base de datos
        dao.UsuarioDAO daoAcceso = new dao.UsuarioDAO();

        // ¡LA MAGIA NUEVA! Ahora guardamos la palabra (el Rol) que nos devuelve el DAO
        String rolUsuario = daoAcceso.validarLogin(usuario, password);

        // Si el resultado NO es "ERROR", ¡significa que la contraseña es correcta y pasamos!
        if (!rolUsuario.equals("ERROR")) {

            // Un mensajito elegante para saber quién entró
            JOptionPane.showMessageDialog(this, "¡Bienvenido al sistema, " + rolUsuario + "!", "Acceso Concedido", JOptionPane.INFORMATION_MESSAGE);

            // Buscamos la VentanaPrincipal que contiene este panel
            Window ventana = SwingUtilities.getWindowAncestor(this);

            // Le damos la orden de encender el sistema
            if (ventana instanceof VentanaPrincipal) {
                ((VentanaPrincipal) ventana).habilitarSistema(rolUsuario);
            }

        } else {
            // Si nos devolvió "ERROR", regañamos y limpiamos
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
            txtPassword.setText(""); // Limpiamos la contraseña
            txtUsuario.requestFocus(); // Regresamos el cursor arriba
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // Si el usuario presiona la tecla ENTER estando en la contraseña...
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLimpiar.doClick(); // ¡Simulamos un clic en el botón Entrar!
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnEntrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrar1ActionPerformed
        // 1. Capturamos los datos que escribiste en la pantalla
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()); // Extraemos la contraseña de forma segura
        String rol = cmbRol.getSelectedItem().toString(); // Tomamos "Administrador" o "Tecnico"

        // 2. Validamos que no intenten crear usuarios fantasma
        if (usuario.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos (Usuario y Contraseña).", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Llamamos a nuestro DAO para hacer el trabajo pesado (encriptar y guardar)
        dao.UsuarioDAO daoUsuario = new dao.UsuarioDAO();
        
        if (daoUsuario.registrarUsuario(usuario, password, rol)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente en el sistema.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // 4. Limpiamos las cajas de texto para dejar el panel impecable
            txtUsuario.setText("");
            txtPassword.setText("");
            cmbRol.setSelectedIndex(0); // Regresamos el combo a la primera opción
            txtUsuario.requestFocus(); // Ponemos el cursor en el primer cuadro
            
            // 5. ¡La magia visual! Recargamos la tabla para ver al nuevo empleado al instante
            cargarTablaUsuarios(); 
        } else {
            // Si falla, normalmente es porque el nombre de usuario ya está repetido en la base de datos
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar. Es posible que este nombre de usuario ya exista.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila = tablaUsuarios.getSelectedRow();
        
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla para modificar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Extraemos los datos ORIGINALES (los que están en la tabla)
        int idUsuario = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());
        String usuarioOriginal = tablaUsuarios.getValueAt(fila, 1).toString();
        String rolOriginal = tablaUsuarios.getValueAt(fila, 2).toString();

        // 2. Extraemos los datos NUEVOS (los que están en las cajas de texto)
        String nuevoUsuario = txtUsuario.getText().trim();
        String nuevoPassword = new String(txtPassword.getPassword());
        String nuevoRol = cmbRol.getSelectedItem().toString();

        // 3. ¡LA NUEVA VALIDACIÓN! ¿Hubo algún cambio real?
        if (nuevoUsuario.equals(usuarioOriginal) && nuevoRol.equals(rolOriginal) && nuevoPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se detectó ningún cambio en los datos.", "Sin Cambios", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return; // Detenemos el proceso aquí para no molestar a la base de datos
        }

        if (nuevoUsuario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre de usuario no puede estar vacío.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ¡PROTECCIÓN DEL JEFE! No puedes quitarte el rol de Administrador a ti mismo (ID 1)
        if (idUsuario == 1 && nuevoRol.equals("Tecnico")) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡No puedes degradar al Administrador principal a Técnico!", "Acción Denegada", javax.swing.JOptionPane.ERROR_MESSAGE);
            cmbRol.setSelectedItem("Administrador");
            return;
        }

        // 4. Si pasó todas las validaciones, llamamos al DAO
        dao.UsuarioDAO daoUsuario = new dao.UsuarioDAO();
        
        if (daoUsuario.modificarUsuario(idUsuario, nuevoUsuario, nuevoPassword, nuevoRol)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            cargarTablaUsuarios();
            txtUsuario.setText("");
            txtPassword.setText("");
            cmbRol.setSelectedIndex(0);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar. Verifique que el nombre de usuario no esté repetido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // 1. Verificamos que haya seleccionado a alguien en la tabla
        int fila = tablaUsuarios.getSelectedRow();
        
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla para eliminar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraemos el ID y el Nombre directamente de la tabla
        int idUsuario = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());
        String nombreUsuario = tablaUsuarios.getValueAt(fila, 1).toString();

        // 3. ¡EL ESCUDO EN ACCIÓN! Evitar que borren al "admin" original (ID 1)
        if (idUsuario == 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡ALERTA!\nNo puedes eliminar la cuenta del Administrador Principal del sistema por motivos de seguridad.", "Acción Denegada", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detenemos todo aquí mismo
        }

        // 4. Confirmación de seguridad de UX (Regla de oro antes de borrar)
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que deseas revocar el acceso y eliminar al usuario: " + nombreUsuario + "?\nEsta acción no se puede deshacer.",
                "Confirmar Eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        // 5. Si el jefe dice que sí, procedemos a borrar
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            
            dao.UsuarioDAO daoUsuario = new dao.UsuarioDAO();
            
            if (daoUsuario.eliminarUsuario(idUsuario)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Acceso revocado. Usuario eliminado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                cargarTablaUsuarios(); // Refrescamos la tabla al instante
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // Averiguamos a qué fila le dio clic
        int fila = tablaUsuarios.getSelectedRow();
        
        if (fila != -1) {
            // Pasamos el Nombre a la caja de texto (La columna 1 es el nombre)
            txtUsuario.setText(tablaUsuarios.getValueAt(fila, 1).toString());
            
            // Pasamos el Rol al ComboBox (La columna 2 es el rol)
            cmbRol.setSelectedItem(tablaUsuarios.getValueAt(fila, 2).toString());
            
            // ¡Seguridad! Dejamos la contraseña en blanco. 
            // Si el jefe quiere cambiarla, que escriba una nueva. Si no, que la deje así.
            txtPassword.setText(""); 
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEntrar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane scrollUsuarios;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
