package gui;
import javax.swing.JOptionPane;


public class PanelEquipos extends javax.swing.JPanel {
    
    private dao.TipoEquipoDAO tipoDAO;
    private int idClienteSeleccionado = -1;
    private java.util.List<Integer> listaIdTipos = new java.util.ArrayList<>();
    private java.util.List<Integer> listaIdMarcas = new java.util.ArrayList<>();
    public PanelEquipos() {
        initComponents();
        tipoDAO = new dao.TipoEquipoDAO();
        
        cargarTipos();
        
        aplicarDisenoEquipos(); 
        
        cargarTablaBuscador("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollBusqueda = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblIdentificador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtImei = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbMarca = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaMouseClicked(evt);
            }
        });
        scrollBusqueda.setViewportView(tablaBusqueda);

        jPanel1.add(scrollBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 460, 110));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO EQUIPOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 44, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        txtModelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 248, -1));

        lblIdentificador.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblIdentificador.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdentificador.setText("IMEI");
        jPanel1.add(lblIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 320, 260, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        txtImei.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 254, -1));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, 44));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar Cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 150, 460, -1));

        cmbTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 255, 30));

        cmbMarca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 254, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));
    }// </editor-fold>//GEN-END:initComponents
    
    private void cargarTipos() {
        cmbTipo.removeAllItems();
        listaIdTipos.clear();

        cmbTipo.addItem("--- Seleccione Tipo ---");
        listaIdTipos.add(-1); 

        dao.TipoEquipoDAO daoTipo = new dao.TipoEquipoDAO();
        for (modelo.TipoEquipo t : daoTipo.listar()) {
            cmbTipo.addItem(t.getNombreTipo());
            listaIdTipos.add(t.getIdTipo());
        }
    }

    private void actualizarMarcas() {
        cmbMarca.removeAllItems();
        listaIdMarcas.clear();

        if (cmbTipo.getSelectedIndex() <= 0) { 
            cmbMarca.addItem("--- Espere ---");
            listaIdMarcas.add(-1);
            lblIdentificador.setText("IMEI / Serie");
            return;
        }

        cmbMarca.addItem("--- Seleccione Marca ---");
        listaIdMarcas.add(-1);

        String tipoSeleccionado = cmbTipo.getSelectedItem().toString();
        int idTipoSeleccionado = listaIdTipos.get(cmbTipo.getSelectedIndex());

        switch (tipoSeleccionado) {
            case "Smartphones":
            case "Tablets":
            case "Smartwatches":
                lblIdentificador.setText("IMEI");
                break;
            case "Computadoras":
                lblIdentificador.setText("Service Tag / S/N");
                break;
            default:
                // Para Consolas, Audio, Impresoras y cualquier otro futuro
                lblIdentificador.setText("N° de Serie");
                break;
        }

        String sql = "SELECT id_marca, nombre_marca FROM marcas WHERE id_tipo = ? ORDER BY nombre_marca ASC";
        
        try (java.sql.Connection con = new factory.ConexionFactory().getConexion();
             java.sql.PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, idTipoSeleccionado);
            
            try (java.sql.ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    cmbMarca.addItem(rs.getString("nombre_marca"));
                    listaIdMarcas.add(rs.getInt("id_marca")); 
                }
            }
        } catch (java.sql.SQLException e) {
            System.err.println("Error al cargar marcas en cascada: " + e.getMessage());
        }
    }
    
    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        String texto = txtCliente.getText().trim();
        cargarTablaBuscador(texto);
    }//GEN-LAST:event_txtClienteKeyReleased
    
    
    private void tablaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaMouseClicked
        int fila = tablaBusqueda.getSelectedRow();
        
        if (fila >= 0) {
            idClienteSeleccionado = Integer.parseInt(tablaBusqueda.getValueAt(fila, 0).toString());
            String nombreCompleto = tablaBusqueda.getValueAt(fila, 2).toString();
            
            txtCliente.setText(nombreCompleto);
        }
    }//GEN-LAST:event_tablaBusquedaMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, busque y seleccione un cliente primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idTipo = listaIdTipos.get(cmbTipo.getSelectedIndex());
        int idMarca = listaIdMarcas.get(cmbMarca.getSelectedIndex());
        
        if (idTipo == -1 || idMarca == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un Tipo y una Marca válidos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String modeloEquipo = txtModelo.getText().trim();
        String imeiSerie = txtImei.getText().trim();

        if (imeiSerie.isEmpty() || imeiSerie.equalsIgnoreCase("N/A")) {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
            imeiSerie = "SN-" + sdf.format(new java.util.Date());
        }

        if (modeloEquipo.isEmpty() || imeiSerie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El modelo y la serie/IMEI son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        modelo.EquipoRegistrado nuevoEquipo = new modelo.EquipoRegistrado(
            idClienteSeleccionado,
            idTipo,
            idMarca,
            modeloEquipo,
            imeiSerie
        );

        dao.EquipoRegistradoDAO daoEquipo = new dao.EquipoRegistradoDAO();

        if (daoEquipo.insertar(nuevoEquipo)) {
            JOptionPane.showMessageDialog(this, "¡Equipo registrado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            txtCliente.setText("");
            cmbTipo.setSelectedIndex(0); 
            txtModelo.setText("");
            txtImei.setText("");
            idClienteSeleccionado = -1; 

            cargarTablaBuscador("");

        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el equipo en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed

        actualizarMarcas();
    
    }//GEN-LAST:event_cmbTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JScrollPane scrollBusqueda;
    private javax.swing.JTable tablaBusqueda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
    
    private void aplicarDisenoEquipos() {

        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(20, 20));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        this.setBackground(new java.awt.Color(240, 244, 248)); // Gris claro web

        // TÍTULO SUPERIOR
        javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Registro de Equipos");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
        lblTitulo.setForeground(new java.awt.Color(44, 62, 80));
        this.add(lblTitulo, java.awt.BorderLayout.NORTH);

        // SECCIÓN IZQUIERDA: BUSCADOR DE CLIENTES
        javax.swing.JPanel panelCentro = new javax.swing.JPanel(new java.awt.BorderLayout(0, 15));
        panelCentro.setOpaque(false);
        
        javax.swing.JPanel panelBusqueda = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        panelBusqueda.setOpaque(false);
        
        javax.swing.JLabel lblBuscar = new javax.swing.JLabel("1. Buscar y Seleccionar Cliente:");
        lblBuscar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        lblBuscar.setForeground(new java.awt.Color(44, 62, 80));
        
        txtCliente.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));
        txtCliente.setPreferredSize(new java.awt.Dimension(0, 40));
        
        panelBusqueda.add(lblBuscar, java.awt.BorderLayout.NORTH);
        panelBusqueda.add(txtCliente, java.awt.BorderLayout.CENTER);
        
        tablaBusqueda.setRowHeight(35);
        tablaBusqueda.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        tablaBusqueda.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        scrollBusqueda.getViewport().setBackground(java.awt.Color.WHITE);
        scrollBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        panelCentro.add(panelBusqueda, java.awt.BorderLayout.NORTH);
        panelCentro.add(scrollBusqueda, java.awt.BorderLayout.CENTER);
        
        this.add(panelCentro, java.awt.BorderLayout.CENTER); // Toma todo el espacio disponible

        // SECCIÓN DERECHA: FORMULARIO DEL EQUIPO
        javax.swing.JPanel panelDerecho = new javax.swing.JPanel(new java.awt.GridBagLayout());
        panelDerecho.setBackground(java.awt.Color.WHITE);
        panelDerecho.setPreferredSize(new java.awt.Dimension(350, 0));
        panelDerecho.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)),
                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 0, 5, 0);
        gbc.weightx = 1.0;
        gbc.gridx = 0;

        javax.swing.JLabel lblSub = new javax.swing.JLabel("2. Datos del Equipo");
        lblSub.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        lblSub.setForeground(java.awt.Color.GRAY);
        gbc.gridy = 0; gbc.insets = new java.awt.Insets(0, 0, 15, 0);
        panelDerecho.add(lblSub, gbc);

        cmbTipo.setPreferredSize(new java.awt.Dimension(0, 35));
        cmbMarca.setPreferredSize(new java.awt.Dimension(0, 35));
        txtModelo.setPreferredSize(new java.awt.Dimension(0, 35));
        txtImei.setPreferredSize(new java.awt.Dimension(0, 35));
        
        lblIdentificador.setForeground(new java.awt.Color(44, 62, 80)); 
        lblIdentificador.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        lblIdentificador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        gbc.insets = new java.awt.Insets(5, 0, 2, 0);
        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Tipo de Equipo:"), gbc);
        gbc.gridy++; panelDerecho.add(cmbTipo, gbc);

        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Marca:"), gbc);
        gbc.gridy++; panelDerecho.add(cmbMarca, gbc);

        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Modelo:"), gbc);
        gbc.gridy++; panelDerecho.add(txtModelo, gbc);

        gbc.gridy++; panelDerecho.add(lblIdentificador, gbc);
        gbc.gridy++; panelDerecho.add(txtImei, gbc);

        gbc.gridy++; gbc.insets = new java.awt.Insets(30, 0, 0, 0);
        btnGuardar.setBackground(new java.awt.Color(46, 204, 113)); 
        btnGuardar.setForeground(java.awt.Color.WHITE);
        btnGuardar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        btnGuardar.setPreferredSize(new java.awt.Dimension(0, 45));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDerecho.add(btnGuardar, gbc);

        gbc.gridy++; gbc.weighty = 1.0;
        panelDerecho.add(javax.swing.Box.createVerticalGlue(), gbc);

        this.add(panelDerecho, java.awt.BorderLayout.EAST);

        this.revalidate();
        this.repaint();
    }
    
    private void cargarTablaBuscador(String filtro) {
        dao.ClienteDAO daoCliente = new dao.ClienteDAO();
        java.util.List<modelo.Cliente> lista;
        
        if (filtro.isEmpty()) {
            lista = daoCliente.listar(); 
        } else {
            lista = daoCliente.buscar(filtro);
        }
        
        java.util.Collections.reverse(lista);
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Identidad", "Cliente"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        for (modelo.Cliente c : lista) {
            modeloTabla.addRow(new Object[]{
                c.getIdCliente(), 
                c.getNumeroIdentidad(), 
                c.getNombre() + " " + c.getApellido()
            });
        }
        
        tablaBusqueda.setModel(modeloTabla);
        
        if (tablaBusqueda.getColumnModel().getColumnCount() > 0) {
            tablaBusqueda.getColumnModel().getColumn(0).setPreferredWidth(40); // ID pequeño
            tablaBusqueda.getColumnModel().getColumn(1).setPreferredWidth(120); // Identidad
            tablaBusqueda.getColumnModel().getColumn(2).setPreferredWidth(250); // Nombre grande
        }
    }
}
