
package gui;

import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import utilidades.GeneradorPDF;

/**
 *
 * @author Ever Chavez
 */
public class PanelListadoOrdenes extends javax.swing.JPanel {

    /**
     * Creates new form PanelListadoOrdenes
     */
    public PanelListadoOrdenes() {
        initComponents();
        cargarTablaGeneral();
        aplicarDisenoListado();
    }
    
    // EL NUEVO MÉTODO PARA EL FILTRO
    // =========================================================================
    // 1. EL MÉTODO ORIGINAL (El que atiende al abrir la ventana y no pide texto)
    // =========================================================================
    public void cargarTablaGeneral() {
        dao.OrdenReparacionDAO dao = new dao.OrdenReparacionDAO();
        java.util.List<Object[]> lista = dao.listarReporteCompleto();
        
        // --- MODELO BLINDADO ---
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[]{"N°", "Cliente", "Equipo", "Problema", "Estado", "Costo"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        
        tablaGeneral.setModel(modelo);
        tablaGeneral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaGeneral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaGeneral.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaGeneral.getColumnModel().getColumn(2).setPreferredWidth(120);
        tablaGeneral.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaGeneral.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaGeneral.getColumnModel().getColumn(5).setPreferredWidth(80);
    }

    // =========================================================================
    // 2. EL MÉTODO NUEVO (El que atiende al ComboBox y SÍ pide un texto de filtro)
    // =========================================================================
        public void cargarTablaGeneral(String estadoFiltro) {
        dao.OrdenReparacionDAO dao = new dao.OrdenReparacionDAO();

        // 1. DECLARAMOS la variable aquí afuera (vacía por ahora)
        java.util.List<Object[]> lista; 

        // 2. Le asignamos valor según el filtro
        if (estadoFiltro.equals("Todos")) {
            lista = dao.listarReporteCompleto(); 
        } else {
            lista = dao.filtrarPorEstado(estadoFiltro); 
        }

        // 3. Ahora el MODELO BLINDADO...
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[]{"N°", "Cliente", "Equipo", "Problema", "Estado", "Costo"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        // 4. ¡AQUÍ YA NO TENDRÁS ERROR! Porque "lista" ya existe para todo el método
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }

        // ... (el resto de tu código de setModel y anchos de columna)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnActualizarOrden = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        scrollTablaGeneral = new javax.swing.JScrollPane();
        tablaGeneral = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdOrden = new javax.swing.JTextField();
        cmbNuevoEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCostoFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarOrden = new javax.swing.JTextField();
        btnEditarDetalles = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        cmbFiltroEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenedor.setBackground(new java.awt.Color(0, 0, 0));
        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panelContenedor.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 44));

        btnActualizarOrden.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnActualizarOrden.setText("Actualizar Orden");
        btnActualizarOrden.addActionListener(this::btnActualizarOrdenActionPerformed);
        panelContenedor.add(btnActualizarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, 90));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panelContenedor.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 44));

        tablaGeneral.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGeneralMouseClicked(evt);
            }
        });
        scrollTablaGeneral.setViewportView(tablaGeneral);

        panelContenedor.add(scrollTablaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 790, 310));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Orden");
        panelContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtIdOrden.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdOrden.setEnabled(false);
        panelContenedor.add(txtIdOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        cmbNuevoEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Recibido", "En Revision", "Reparado", "Entregado", "Sin Reparacion" }));
        panelContenedor.add(cmbNuevoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 150, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Orden N°");
        panelContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtCostoFinal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelContenedor.add(txtCostoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo Final");
        panelContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txtBuscarOrden.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBuscarOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenKeyReleased(evt);
            }
        });
        panelContenedor.add(txtBuscarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 290, 30));

        btnEditarDetalles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditarDetalles.setText("Editar Detalles");
        btnEditarDetalles.addActionListener(this::btnEditarDetallesActionPerformed);
        panelContenedor.add(btnEditarDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 150, 40));

        btnEntregar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(this::btnEntregarActionPerformed);
        panelContenedor.add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, 44));

        cmbFiltroEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Recibido", "En Reparacion", "Listo para Entrega", "Entregado" }));
        cmbFiltroEstado.addItemListener(this::cmbFiltroEstadoItemStateChanged);
        panelContenedor.add(cmbFiltroEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 30));

        jPanel1.add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGeneralMouseClicked
        int fila = tablaGeneral.getSelectedRow();
        
        if (fila >= 0) {
            // 1. ID de Orden (Columna 0)
            txtIdOrden.setText(tablaGeneral.getValueAt(fila, 0).toString());
            
            // 2. Estado (Columna 4)
            Object valorEstado = tablaGeneral.getValueAt(fila, 4);
            if (valorEstado != null) {
                cmbNuevoEstado.setSelectedItem(valorEstado.toString().trim());
            }
            
            // 3. Costo (Columna 5)
            Object valorCosto = tablaGeneral.getValueAt(fila, 5);
            txtCostoFinal.setText(valorCosto != null ? valorCosto.toString() : "0.0");
        }
    }//GEN-LAST:event_tablaGeneralMouseClicked

    private void btnActualizarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarOrdenActionPerformed
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden de la tabla.");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdOrden.getText());
            String estado = cmbNuevoEstado.getSelectedItem().toString();
            
            // Limpiamos el texto del costo por si tiene espacios
            String costoTexto = txtCostoFinal.getText().trim();
            double costo = Double.parseDouble(costoTexto);

            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
            if (daoOrden.actualizarEstadoYCosto(id, estado, costo)) {
                JOptionPane.showMessageDialog(this, "¡Orden actualizada correctamente!");
                cargarTablaGeneral(); 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un costo válido (ej: 150.00)");
        }
    }//GEN-LAST:event_btnActualizarOrdenActionPerformed

    private void txtBuscarOrdenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenKeyReleased
        String texto = txtBuscarOrden.getText().trim();
        dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
        
        java.util.List<Object[]> lista = texto.isEmpty() ? 
                                         daoOrden.listarReporteCompleto() : 
                                         daoOrden.buscarOrden(texto);
        
        // --- MODELO BLINDADO ---
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new Object[]{"N° Orden", "Cliente", "Equipo", "Problema", "Estado", "Costo"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        
        tablaGeneral.setModel(modelo);
        tablaGeneral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaGeneral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaGeneral.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaGeneral.getColumnModel().getColumn(2).setPreferredWidth(120);
        tablaGeneral.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaGeneral.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaGeneral.getColumnModel().getColumn(5).setPreferredWidth(80);
    }//GEN-LAST:event_txtBuscarOrdenKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // 1. Validar que haya tocado una orden
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una orden de la tabla para eliminarla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pedir confirmación (NUNCA borrar directo)
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar la Orden N° " + txtIdOrden.getText() + "?\nEsta acción no se puede deshacer.", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtIdOrden.getText());
            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
            
            if (daoOrden.eliminar(id)) {
                JOptionPane.showMessageDialog(this, "Orden eliminada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiamos los campos y refrescamos la tabla
                txtIdOrden.setText("");
                cmbNuevoEstado.setSelectedIndex(0);
                txtCostoFinal.setText("");
                cargarTablaGeneral(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la orden.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDetallesActionPerformed
        // 1. Validar que haya seleccionado una orden
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden de la tabla primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idOrden = Integer.parseInt(txtIdOrden.getText());
        dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
        
        // 2. Traer los datos actuales
        String[] textosActuales = daoOrden.obtenerTextosOrden(idOrden);
        String problemaActual = textosActuales[0] != null ? textosActuales[0] : "";
        String trabajoActual = textosActuales[1] != null ? textosActuales[1] : "";

        // 3. Crear los JTextArea por código
        javax.swing.JTextArea txtProblema = new javax.swing.JTextArea(5, 30);
        txtProblema.setText(problemaActual);
        txtProblema.setLineWrap(true);
        txtProblema.setWrapStyleWord(true);
        
        javax.swing.JTextArea txtTrabajo = new javax.swing.JTextArea(5, 30);
        txtTrabajo.setText(trabajoActual);
        txtTrabajo.setLineWrap(true);
        txtTrabajo.setWrapStyleWord(true);

        // 4. Armar el panel flotante
        javax.swing.JPanel panelEdicion = new javax.swing.JPanel(new java.awt.GridLayout(4, 1, 5, 5));
        panelEdicion.add(new javax.swing.JLabel("Problema Reportado:"));
        panelEdicion.add(new javax.swing.JScrollPane(txtProblema));
        panelEdicion.add(new javax.swing.JLabel("Trabajo Realizado:"));
        panelEdicion.add(new javax.swing.JScrollPane(txtTrabajo));

        // 5. Mostrar la ventana y esperar a que el usuario le dé a "Aceptar"
        int opcion = JOptionPane.showConfirmDialog(this, panelEdicion, "Editando Orden N° " + idOrden, 
                                                   JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        // 6. Si el usuario le dio a "OK", guardamos en la base de datos
        if (opcion == JOptionPane.OK_OPTION) {
            String nuevoProblema = txtProblema.getText().trim();
            String nuevoTrabajo = txtTrabajo.getText().trim();
            
            if (daoOrden.actualizarTextosOrden(idOrden, nuevoProblema, nuevoTrabajo)) {
                JOptionPane.showMessageDialog(this, "Detalles actualizados correctamente.");
                cargarTablaGeneral(); // Refrescar la tabla para ver el nuevo problema
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar los detalles.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarDetallesActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        int fila = tablaGeneral.getSelectedRow(); 
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una orden.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Extraemos y LIMPIAMOS los datos (Importante el .trim())
        String idOrden = tablaGeneral.getValueAt(fila, 0).toString().trim();
        String cliente = tablaGeneral.getValueAt(fila, 1).toString().trim();
        String equipo = tablaGeneral.getValueAt(fila, 2).toString().trim();
        String problema = tablaGeneral.getValueAt(fila, 3).toString().trim();
        String estadoActual = tablaGeneral.getValueAt(fila, 4).toString().trim();
        String costoTotal = tablaGeneral.getValueAt(fila, 5).toString().trim();

        if (estadoActual.equals("Entregado")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta orden ya fue entregada anteriormente.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Confirmar entrega y cobro de L. " + costoTotal + "?", "Sairtech", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO(); 
            
            // Traemos el trabajo realizado de la BD
            String[] detalles = daoOrden.obtenerTextosOrden(Integer.parseInt(idOrden));
            String trabajoRealizado = (detalles[1] != null && !detalles[1].isEmpty()) ? detalles[1] : "Revisión técnica general.";

            if (daoOrden.marcarComoEntregado(Integer.parseInt(idOrden))) {
                try {
                    // A. Datos del técnico
                    gui.VentanaPrincipal v = (gui.VentanaPrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
                    String tecnicoActivo = v.getNombreUsuarioActivo();
                    
                    // B. GENERAR EL PDF
                    utilidades.GeneradorPDF generador = new utilidades.GeneradorPDF();
                    boolean ticketCreado = generador.crearTicket(
                        idOrden, cliente, equipo, problema, costoTotal,
                        "SAIRTECH", "1601-2003-XXXXXX", "Santa Bárbara, HN", "+504 9999-9999", 
                        "Garantía de 30 días en mano de obra.", tecnicoActivo, trabajoRealizado,
                        false // <--- ¡FALSE! Le decimos explícitamente que NO es recepción (Es Factura)
                    );
                    
                   if (ticketCreado) {
                        javax.swing.JOptionPane.showMessageDialog(this, "¡Entrega exitosa! Factura generada.");
                        cargarTablaGeneral(); // Solo refrescamos la tabla
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo crear el ticket.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    System.err.println("Error crítico al entregar: " + ex.getMessage());
                    ex.printStackTrace(); // Esto nos dirá en consola exactamente qué falló
                }
            }
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void cmbFiltroEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFiltroEstadoItemStateChanged

        String estadoSeleccionado = cmbFiltroEstado.getSelectedItem().toString();
        // Llamas a tu método de llenar tabla pero pasándole el filtro
        cargarTablaGeneral(estadoSeleccionado);

    }//GEN-LAST:event_cmbFiltroEstadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarOrden;
    private javax.swing.JButton btnEditarDetalles;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbFiltroEstado;
    private javax.swing.JComboBox<String> cmbNuevoEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JScrollPane scrollTablaGeneral;
    private javax.swing.JTable tablaGeneral;
    private javax.swing.JTextField txtBuscarOrden;
    private javax.swing.JTextField txtCostoFinal;
    private javax.swing.JTextField txtIdOrden;
    // End of variables declaration//GEN-END:variables
    private void aplicarDisenoListado() {
        // 1. Limpieza total del panel viejo
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(20, 20));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        this.setBackground(new java.awt.Color(240, 244, 248)); // Gris claro moderno

        // 2. PANEL NORTE: Título y Herramientas de búsqueda
        javax.swing.JPanel panelNorte = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        panelNorte.setOpaque(false);
        
        // 3. LA TABLA (CENTRO)
        tablaGeneral.setRowHeight(35);
        tablaGeneral.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        tablaGeneral.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        scrollTablaGeneral.getViewport().setBackground(java.awt.Color.WHITE);
        scrollTablaGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        
        // Bloqueamos el redimensionamiento automático para usar Scroll horizontal si es necesario
        tablaGeneral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        
        this.add(scrollTablaGeneral, java.awt.BorderLayout.CENTER);
        
        javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Listado Órdenes");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        lblTitulo.setForeground(new java.awt.Color(44, 62, 80));
        
        // Panel derecho para agrupar Buscador y ComboBox
        javax.swing.JPanel panelHerramientas = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 0));
        panelHerramientas.setOpaque(false);
        
        // Estilo para tus componentes existentes
        txtBuscarOrden.setPreferredSize(new java.awt.Dimension(250, 35));
        cmbFiltroEstado.setPreferredSize(new java.awt.Dimension(180, 35));
        
        panelHerramientas.add(new javax.swing.JLabel("🔍 Buscar:"));
        panelHerramientas.add(txtBuscarOrden);
        panelHerramientas.add(new javax.swing.JLabel("Filtrar Estado:"));
        panelHerramientas.add(cmbFiltroEstado);

        panelNorte.add(lblTitulo, java.awt.BorderLayout.WEST);
        panelNorte.add(panelHerramientas, java.awt.BorderLayout.EAST);
        this.add(panelNorte, java.awt.BorderLayout.NORTH);

        // 4. PANEL DE GESTIÓN DERECHO (ESTE)
        javax.swing.JPanel panelDerecho = new javax.swing.JPanel(new java.awt.GridBagLayout());
        panelDerecho.setBackground(java.awt.Color.WHITE);
        panelDerecho.setPreferredSize(new java.awt.Dimension(320, 0)); // Ancho fijo elegante
        panelDerecho.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)),
                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(10, 0, 5, 0);
        gbc.weightx = 1.0;
        gbc.gridx = 0;

        // Título del formulario
        javax.swing.JLabel lblSub = new javax.swing.JLabel("Gestión de Orden");
        lblSub.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        lblSub.setForeground(java.awt.Color.GRAY);
        gbc.gridy = 0;
        panelDerecho.add(lblSub, gbc);

        // Campos de edición rápida (Tus variables de NetBeans)
        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Orden N°:"), gbc);
        txtIdOrden.setPreferredSize(new java.awt.Dimension(0, 35));
        gbc.gridy++; panelDerecho.add(txtIdOrden, gbc);
        
        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Actualizar Estado:"), gbc);
        cmbNuevoEstado.setPreferredSize(new java.awt.Dimension(0, 35));
        gbc.gridy++; panelDerecho.add(cmbNuevoEstado, gbc);

        gbc.gridy++; panelDerecho.add(new javax.swing.JLabel("Costo Final (L.):"), gbc);
        txtCostoFinal.setPreferredSize(new java.awt.Dimension(0, 35));
        gbc.gridy++; panelDerecho.add(txtCostoFinal, gbc);

        // Espacio para los botones de acción
        gbc.gridy++; gbc.insets = new java.awt.Insets(25, 0, 0, 0);

        // Panel de botones apilados
        javax.swing.JPanel panelAcciones = new javax.swing.JPanel(new java.awt.GridLayout(3, 1, 0, 10));
        panelAcciones.setOpaque(false);

        // Estilizamos tus botones con colores y el "Hand Cursor"
        btnActualizarOrden.setBackground(new java.awt.Color(52, 152, 219)); 
        btnActualizarOrden.setForeground(java.awt.Color.WHITE);
        btnActualizarOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        btnEditarDetalles.setBackground(new java.awt.Color(155, 89, 182)); 
        btnEditarDetalles.setForeground(java.awt.Color.WHITE);
        btnEditarDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        btnEntregar.setBackground(new java.awt.Color(46, 204, 113)); 
        btnEntregar.setForeground(java.awt.Color.WHITE);
        btnEntregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelAcciones.add(btnActualizarOrden);
        panelAcciones.add(btnEditarDetalles);
        panelAcciones.add(btnEntregar);
        
        gbc.gridy++; panelDerecho.add(panelAcciones, gbc);

        // Botón Eliminar al fondo (Rojo)
        gbc.insets = new java.awt.Insets(40, 0, 0, 0);
        btnEliminar.setBackground(new java.awt.Color(231, 76, 60)); 
        btnEliminar.setForeground(java.awt.Color.WHITE);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gbc.gridy++; panelDerecho.add(btnEliminar, gbc);

        // Empujador invisible para que todo se quede arriba
        gbc.gridy++; gbc.weighty = 1.0;
        panelDerecho.add(javax.swing.Box.createVerticalGlue(), gbc);

        // 5. ENSAMBLAR AL LADO DERECHO
        this.add(panelDerecho, java.awt.BorderLayout.EAST);
        
        this.revalidate();
        this.repaint();
    }
}
