
package gui;


/**
 *
 * @author Ever Chavez
 */
public class PanelEstadisticas extends javax.swing.JPanel {

    
    public PanelEstadisticas() {
        initComponents();
        cargarEstadisticas();
        aplicarNuevoDiseno();
        iniciarReloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPendientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEntregados = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblGanancias = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1027, 627));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setForeground(new java.awt.Color(0, 51, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Equipos Pendientes");

        lblPendientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPendientes.setForeground(new java.awt.Color(255, 255, 255));
        lblPendientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPendientes.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPendientes)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 110));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipos Entregados");

        lblEntregados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEntregados.setForeground(new java.awt.Color(255, 255, 255));
        lblEntregados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntregados.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
            .addComponent(lblEntregados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEntregados)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setForeground(new java.awt.Color(0, 51, 204));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ganancias Totales");

        lblGanancias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblGanancias.setForeground(new java.awt.Color(255, 255, 255));
        lblGanancias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGanancias.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
            .addComponent(lblGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGanancias)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, -1));
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblFecha;
    
    private void cargarEstadisticas() {
        dao.EstadisticasDAO daoEstadisticas = new dao.EstadisticasDAO();
        modelo.Estadisticas datos = daoEstadisticas.obtenerNumerosMagicos();

        // Asumiendo que le pusiste estos nombres a tus JLabels de números grandes:
        lblEntregados.setText(String.valueOf(datos.getEquiposEntregados()));
        lblPendientes.setText(String.valueOf(datos.getOrdenesPendientes()));
        
        // Formateamos el dinero con dos decimales y el símbolo de Lempiras
        String dineroFormateado = String.format("L. %.2f", datos.getGananciasTotales());
        lblGanancias.setText(dineroFormateado);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblEntregados;
    private javax.swing.JLabel lblGanancias;
    private javax.swing.JLabel lblPendientes;
    // End of variables declaration//GEN-END:variables
    // ==========================================================
    // DISEÑO MODERNO CON LIBRERÍAS NATIVAS DE JAVA (Cero descargas)
    // ==========================================================
    private void aplicarNuevoDiseno() {
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(20, 20));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 30, 30));
        this.setBackground(new java.awt.Color(240, 244, 248));

        // 1. --- PANEL DE CABECERA (SALUDO + TIEMPO) ---
        javax.swing.JPanel panelCabecera = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelCabecera.setOpaque(false);

        javax.swing.JLabel lblSaludo = new javax.swing.JLabel("Resumen Operativo Sairtech");
        lblSaludo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
        lblSaludo.setForeground(new java.awt.Color(44, 62, 80));

        javax.swing.JPanel panelTiempo = new javax.swing.JPanel(new java.awt.GridLayout(2, 1));
        panelTiempo.setOpaque(false);

        lblFecha = new javax.swing.JLabel();
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        lblFecha.setForeground(java.awt.Color.GRAY);

        lblReloj = new javax.swing.JLabel();
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReloj.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        lblReloj.setForeground(new java.awt.Color(52, 152, 219));

        panelTiempo.add(lblFecha);
        panelTiempo.add(lblReloj);

        panelCabecera.add(lblSaludo, java.awt.BorderLayout.WEST);
        panelCabecera.add(panelTiempo, java.awt.BorderLayout.EAST);

        // 2. --- PANEL DE TARJETAS ---
        javax.swing.JPanel panelTarjetas = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 20, 0));
        panelTarjetas.setOpaque(false);
        panelTarjetas.setPreferredSize(new java.awt.Dimension(0, 120));

        estilizarTarjeta(jPanel3, jLabel3, lblGanancias, new java.awt.Color(46, 204, 113));
        estilizarTarjeta(jPanel1, jLabel1, lblEntregados, new java.awt.Color(52, 152, 219));
        estilizarTarjeta(jPanel2, jLabel2, lblPendientes, new java.awt.Color(231, 76, 60));

        panelTarjetas.add(jPanel3);
        panelTarjetas.add(jPanel1);
        panelTarjetas.add(jPanel2);

        // Contenedor Maestro Norte (Junta Cabecera + Tarjetas)
        javax.swing.JPanel contenedorNorte = new javax.swing.JPanel(new java.awt.BorderLayout(0, 20));
        contenedorNorte.setOpaque(false);
        contenedorNorte.add(panelCabecera, java.awt.BorderLayout.NORTH);
        contenedorNorte.add(panelTarjetas, java.awt.BorderLayout.CENTER);

        // 3. --- PANEL CENTRAL (CARDLAYOUT: GRÁFICO / TABLA) ---
        javax.swing.JPanel panelCentro = new javax.swing.JPanel(new java.awt.BorderLayout());
        panelCentro.setBackground(java.awt.Color.WHITE);
        panelCentro.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)),
                "Estadísticas de Equipos en Taller",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14),
                java.awt.Color.GRAY));

        // Radio Buttons (Controles)
        javax.swing.JPanel panelControles = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        panelControles.setBackground(java.awt.Color.WHITE);
        javax.swing.JRadioButton rbtnGrafico = new javax.swing.JRadioButton("Vista Gráfico", true);
        javax.swing.JRadioButton rbtnTabla = new javax.swing.JRadioButton("Vista Tabla");
        rbtnGrafico.setBackground(java.awt.Color.WHITE);
        rbtnTabla.setBackground(java.awt.Color.WHITE);

        javax.swing.ButtonGroup grupoVistas = new javax.swing.ButtonGroup();
        grupoVistas.add(rbtnGrafico);
        grupoVistas.add(rbtnTabla);
        panelControles.add(rbtnGrafico);
        panelControles.add(rbtnTabla);
        panelCentro.add(panelControles, java.awt.BorderLayout.NORTH);

        // Layout de Cartas
        java.awt.CardLayout layoutCartas = new java.awt.CardLayout();
        javax.swing.JPanel panelCartas = new javax.swing.JPanel(layoutCartas);
        panelCartas.setOpaque(false);

        // Datos BD
        dao.EstadisticasDAO daoEst = new dao.EstadisticasDAO();
        java.util.Map<String, Integer> datosBD = daoEst.obtenerDatosGraficoEquipos();

        // --- CARTA 1: GRÁFICO ---
        org.jfree.data.general.DefaultPieDataset ds = new org.jfree.data.general.DefaultPieDataset();
        if (!datosBD.isEmpty()) {
            datosBD.forEach(ds::setValue);
        } else {
            ds.setValue("Sin datos", 1);
        }

        org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createPieChart("", ds, true, true, false);
        chart.setBackgroundPaint(java.awt.Color.WHITE);
        org.jfree.chart.plot.PiePlot plot = (org.jfree.chart.plot.PiePlot) chart.getPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setOutlineVisible(false);
        plot.setToolTipGenerator(new org.jfree.chart.labels.StandardPieToolTipGenerator("{0}: {1} ({2})", new java.text.DecimalFormat("0"), new java.text.DecimalFormat("0.0%")));

        org.jfree.chart.ChartPanel cp = new org.jfree.chart.ChartPanel(chart);
        cp.setBackground(java.awt.Color.WHITE);
        panelCartas.add(cp, "CARTA_GRAFICO");

        // --- CARTA 2: TABLA ---
        String[] cols = {"Tipo de Equipo", "Cantidad"};
        javax.swing.table.DefaultTableModel mod = new javax.swing.table.DefaultTableModel(cols, 0);
        datosBD.forEach((k, v) -> mod.addRow(new Object[]{k, v}));
        javax.swing.JTable t = new javax.swing.JTable(mod);
        t.setRowHeight(30);
        javax.swing.JScrollPane sp = new javax.swing.JScrollPane(t);
        sp.getViewport().setBackground(java.awt.Color.WHITE);
        panelCartas.add(sp, "CARTA_TABLA");

        panelCentro.add(panelCartas, java.awt.BorderLayout.CENTER);

        // Listeners
        rbtnGrafico.addActionListener(e -> layoutCartas.show(panelCartas, "CARTA_GRAFICO"));
        rbtnTabla.addActionListener(e -> layoutCartas.show(panelCartas, "CARTA_TABLA"));

        // Ensamblado
        this.add(contenedorNorte, java.awt.BorderLayout.NORTH);
        this.add(panelCentro, java.awt.BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    // Método para cambiar el diseño de los paneles generados por NetBeans
    private void estilizarTarjeta(javax.swing.JPanel panel, javax.swing.JLabel titulo, javax.swing.JLabel valor, java.awt.Color colorBorde) {
        // Quitamos el diseño AbsoluteLayout viejo y usamos GridLayout (2 filas, 1 columna)
        panel.setLayout(new java.awt.GridLayout(2, 1)); 
        panel.setBackground(java.awt.Color.WHITE);
        
        panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, colorBorde), // Borde superior de color
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15) // Relleno interior
        ));
        
        // Centramos y estilizamos el título
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setForeground(java.awt.Color.GRAY);
        titulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        
        // Centramos y estilizamos el número grande
        valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor.setForeground(new java.awt.Color(44, 62, 80));
        valor.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36));
    }
    private void iniciarReloj() {
        // Formato para la fecha: Lunes, 01 de Abril de 2026
        java.text.SimpleDateFormat sdfFecha = new java.text.SimpleDateFormat("EEEE, dd 'de' MMMM 'de' yyyy", new java.util.Locale("es", "ES"));
        lblFecha.setText(sdfFecha.format(new java.util.Date()));

        // Timer que se ejecuta cada 1 segundo (1000 ms)
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            java.text.SimpleDateFormat sdfHora = new java.text.SimpleDateFormat("hh:mm:ss a");
            lblReloj.setText(sdfHora.format(new java.util.Date()));
        });
        timer.start();
    }
}
