package gui;
import javax.swing.JOptionPane;


public class PanelEquipos extends javax.swing.JPanel {
    
    private int idClienteSeleccionado = -1;
    private java.util.List<Integer> listaIdTipos = new java.util.ArrayList<>();
    private java.util.List<Integer> listaIdMarcas = new java.util.ArrayList<>();
    public PanelEquipos() {
        initComponents();
        scrollBusqueda.setVisible(false);
        cargarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollBusqueda = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtImei = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        cmbMarca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaMouseClicked(evt);
            }
        });
        scrollBusqueda.setViewportView(tablaBusqueda);

        jPanel1.add(scrollBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 530, 210));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO EQUIPOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 44, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 223, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 305, -1, -1));

        txtModelo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 302, 248, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IMEI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 305, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 229, -1, -1));

        txtImei.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(txtImei, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 302, 254, -1));

        Eliminar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Eliminar.setText("Eliminar");
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 391, -1, 44));

        jButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton2.setText("Modificar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 391, -1, 44));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 391, -1, 44));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar Cliente");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 145, -1, -1));

        txtCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 142, 529, -1));

        cmbTipo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 223, 255, 37));

        cmbMarca.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 223, 254, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. Validar que se haya seleccionado un cliente con la búsqueda en vivo
        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, busque y seleccione un cliente primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Obtener los IDs de los Combobox usando las listas paralelas
        // SelectedIndex nos dice qué posición tocó el usuario (0, 1, 2...)
        int idTipo = listaIdTipos.get(cmbTipo.getSelectedIndex());
        int idMarca = listaIdMarcas.get(cmbMarca.getSelectedIndex());

        // 3. Capturar Modelo e IMEI/Serie
        String modeloEquipo = txtModelo.getText().trim();
        String imeiSerie = txtImei.getText().trim();

        // Si el IMEI viene vacío, le generamos uno único temporal
        if (imeiSerie.isEmpty() || imeiSerie.equalsIgnoreCase("N/A")) {
            // Creamos un código único basado en la hora exacta: SN-202603291720
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
            imeiSerie = "SN-" + sdf.format(new java.util.Date());
        }

        // 4. Validación básica
        if (modeloEquipo.isEmpty() || imeiSerie.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El modelo y la serie/IMEI son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 5. Crear el objeto del Modelo
        modelo.EquipoRegistrado nuevoEquipo = new modelo.EquipoRegistrado(
                idClienteSeleccionado, 
                idTipo, 
                idMarca, 
                modeloEquipo, 
                imeiSerie
        );

        // 6. Llamar al DAO para guardar
        dao.EquipoRegistradoDAO daoEquipo = new dao.EquipoRegistradoDAO();
        
        if (daoEquipo.insertar(nuevoEquipo)) {
            JOptionPane.showMessageDialog(this, "¡Equipo registrado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // 7. Limpiar el formulario
            txtCliente.setText("");
            txtModelo.setText("");
            txtImei.setText("");
            idClienteSeleccionado = -1; // Reset del cliente
            scrollBusqueda.setVisible(false); // Ocultar tabla de búsqueda si quedó abierta
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el equipo en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        String texto = txtCliente.getText().trim();
        
        // Si el técnico borra todo, ocultamos la tabla
        if (texto.isEmpty()) {
            scrollBusqueda.setVisible(false);
            return;
        }
        
        // Buscamos en la BD
        dao.ClienteDAO daoCliente = new dao.ClienteDAO();
        java.util.List<modelo.Cliente> lista = daoCliente.buscar(texto);
        
        // Configuramos la tabla para mostrar los resultados
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Identidad");
        modeloTabla.addColumn("Cliente");
        
        for (modelo.Cliente c : lista) {
            Object[] fila = new Object[3];
            fila[0] = c.getIdCliente();
            fila[1] = c.getNumeroIdentidad();
            fila[2] = c.getNombre() + " " + c.getApellido();
            modeloTabla.addRow(fila);
        }
        
        tablaBusqueda.setModel(modeloTabla);
        
        // Si encontró algo, mostramos la tabla mágica
        if (lista.size() > 0) {
            scrollBusqueda.setVisible(true);
        } else {
            scrollBusqueda.setVisible(false);
        }
    }//GEN-LAST:event_txtClienteKeyReleased
    
    private void cargarCombos() {
        // 1. Llenar Tipos
        dao.TipoEquipoDAO daoTipo = new dao.TipoEquipoDAO();
        cmbTipo.removeAllItems();
        listaIdTipos.clear();
        for (modelo.TipoEquipo t : daoTipo.listar()) {
            cmbTipo.addItem(t.getNombreTipo());
            listaIdTipos.add(t.getIdTipo()); // Guardamos el ID en la misma posición
        }

        // 2. Llenar Marcas
        dao.MarcaDAO daoMarca = new dao.MarcaDAO();
        cmbMarca.removeAllItems();
        listaIdMarcas.clear();
        for (modelo.Marca m : daoMarca.listar()) {
            cmbMarca.addItem(m.getNombreMarca());
            listaIdMarcas.add(m.getIdMarca()); // Guardamos el ID en la misma posición
        }
    }
    
    private void tablaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaMouseClicked
        int fila = tablaBusqueda.getSelectedRow();
        
        if (fila >= 0) {
            // Capturamos el ID oculto de la columna 0 y el nombre de la columna 2
            idClienteSeleccionado = (int) tablaBusqueda.getValueAt(fila, 0);
            String nombreCompleto = tablaBusqueda.getValueAt(fila, 2).toString();
            
            // Ponemos el nombre en la caja de texto
            txtCliente.setText(nombreCompleto);
            
            // Desaparecemos la tabla
            scrollBusqueda.setVisible(false);
        }
    }//GEN-LAST:event_tablaBusquedaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollBusqueda;
    private javax.swing.JTable tablaBusqueda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
