package gui;
import javax.swing.JOptionPane;

public class PanelClientes extends javax.swing.JPanel {

    private int idClienteSeleccionado = -1;
    public PanelClientes() {
        
        initComponents();
        this.setSize(1200, 750);
        cargarTablaClientes("");
        aplicarDisenoClientes();
    }
    // Método para llenar la tabla principal de clientes
    private void cargarTablaClientes(String textoBusqueda) {
        dao.ClienteDAO dao = new dao.ClienteDAO();
        java.util.List<modelo.Cliente> lista;   
        
        // Si no hay texto de búsqueda, mostramos todos. Si hay texto, usamos la búsqueda en vivo.
        if (textoBusqueda.isEmpty()) {
            lista = dao.listar();
        } else {
            lista = dao.buscar(textoBusqueda);
        }
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        // --- 2. AGREGAMOS LAS COLUMNAS ---
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Identidad");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Teléfono");
        modeloTabla.addColumn("Correo");
        
        // Llenamos las filas separando nombre y apellido
        for (modelo.Cliente c : lista) {
            Object[] fila = new Object[6];
            fila[0] = c.getIdCliente();
            fila[1] = c.getNumeroIdentidad();
            fila[2] = c.getNombre();
            fila[3] = c.getApellido();
            fila[4] = c.getTelefono();
            fila[5] = c.getCorreo();
            modeloTabla.addRow(fila);
        }
        
        // Se lo aplicamos a tu tabla visual
        tablaClientes.setModel(modeloTabla);
        // --- NUEVO: Ajuste visual de las columnas ---
        // Le damos el ancho ideal a cada columna (en píxeles) para que todo se lea perfecto
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setPreferredWidth(40);  // ID (Pequeño)
            tablaClientes.getColumnModel().getColumn(1).setPreferredWidth(130); // Identidad
            tablaClientes.getColumnModel().getColumn(2).setPreferredWidth(140); // Nombre
            tablaClientes.getColumnModel().getColumn(3).setPreferredWidth(140); // Apellido
            tablaClientes.getColumnModel().getColumn(4).setPreferredWidth(100); // Teléfono
            tablaClientes.getColumnModel().getColumn(5).setPreferredWidth(200); // Correo (El más grande)
        }
        
        // --- NUEVO: Ajuste visual de las columnas ---
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setPreferredWidth(50);  
            tablaClientes.getColumnModel().getColumn(1).setPreferredWidth(150); 
            tablaClientes.getColumnModel().getColumn(2).setPreferredWidth(160); 
            tablaClientes.getColumnModel().getColumn(3).setPreferredWidth(160); 
            tablaClientes.getColumnModel().getColumn(4).setPreferredWidth(120); 
            tablaClientes.getColumnModel().getColumn(5).setPreferredWidth(250); 
            
            // ¡ESTA ES LA LÍNEA MÁGICA! Le prohíbe a Java aplastar las celdas
            tablaClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollBusqueda = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        scrollBusqueda.setViewportView(tablaClientes);

        jPanel1.add(scrollBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 740, 110));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 262, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 312, -1, 30));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 254, -1));

        txtTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 254, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 312, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, 30));

        txtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 250, -1));

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 250, -1));

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, 44));

        btnModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, 44));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, 44));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 362, -1, 30));

        txtIdentidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(txtIdentidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 254, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 450, -1));

        btnLimpiar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, 44));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 780, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String identidad = txtIdentidad.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();

        if (identidad.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        modelo.Cliente nuevoCliente = new modelo.Cliente(identidad, nombre, apellido, telefono, correo);
        dao.ClienteDAO dao = new dao.ClienteDAO();
        
        if (dao.insertar(nuevoCliente)) {
            JOptionPane.showMessageDialog(this, "¡Cliente guardado exitosamente!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiamos las cajas
            txtIdentidad.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
            txtCliente.setText(""); // Limpiamos el buscador
            
            // Recargamos la tabla para que aparezca el nuevo al instante
            cargarTablaClientes(""); 
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar. Verifique si la identidad ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        // Capturamos lo que el usuario escribe
        String texto = txtCliente.getText().trim();

        // Llamamos a tu método que ya hace toda la magia de buscar y armar las 6 columnas
        cargarTablaClientes(texto);
    }//GEN-LAST:event_txtClienteKeyReleased

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // Averiguamos qué fila tocó el usuario
        int fila = tablaClientes.getSelectedRow();
        
        if (fila >= 0) {
            try {
                // Columna 0: Guardamos el ID en secreto
                idClienteSeleccionado = Integer.parseInt(tablaClientes.getValueAt(fila, 0).toString());
                
                // Columna 1 a 5: Extraemos de forma súper segura (evita que el programa explote si hay nulos)
                Object identidad = tablaClientes.getValueAt(fila, 1);
                txtIdentidad.setText(identidad != null ? identidad.toString() : "");
                
                Object nombre = tablaClientes.getValueAt(fila, 2);
                txtNombre.setText(nombre != null ? nombre.toString() : "");
                
                Object apellido = tablaClientes.getValueAt(fila, 3);
                txtApellido.setText(apellido != null ? apellido.toString() : "");
                
                Object telefono = tablaClientes.getValueAt(fila, 4);
                txtTelefono.setText(telefono != null ? telefono.toString() : "");
                
                Object correo = tablaClientes.getValueAt(fila, 5);
                txtCorreo.setText(correo != null ? correo.toString() : "");
                
                // TRUCO DE UX: Deshabilitamos Guardar
                btnGuardar.setEnabled(false);
                
                // Si ya tienes tus botones en el diseño, puedes descomentar esto:
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnLimpiar.setEnabled(true);
                
            } catch (Exception e) {
                // Si algo falla, te mostrará una ventanita diciéndote exactamente qué se rompió
                javax.swing.JOptionPane.showMessageDialog(this, "Error al leer la tabla: " + e.getMessage());
                System.err.println("Error técnico: " + e);
            }
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Capturamos los datos actuales de los campos
        String identidadActual = txtIdentidad.getText().trim();
        String nombreActual = txtNombre.getText().trim();
        String apellidoActual = txtApellido.getText().trim();
        String telefonoActual = txtTelefono.getText().trim();
        String correoActual = txtCorreo.getText().trim();

        // 2. Recuperamos los datos de la fila seleccionada en la tabla para comparar
        int fila = tablaClientes.getSelectedRow();
        
        // Asumiendo que Identidad, Nombre y Apellido son obligatorios en tu BD, pueden quedar con toString()
        String identidadTabla = tablaClientes.getValueAt(fila, 1).toString();
        String nombreTabla = tablaClientes.getValueAt(fila, 2).toString();
        String apellidoTabla = tablaClientes.getValueAt(fila, 3).toString();
        
        Object telefonoObj = tablaClientes.getValueAt(fila, 4);
        String telefonoTabla = (telefonoObj != null) ? telefonoObj.toString() : "";
        
        Object correoObj = tablaClientes.getValueAt(fila, 5);
        String correoTabla = (correoObj != null) ? correoObj.toString() : "";

        // 3. COMPARACIÓN: Si todo es exactamente igual, le avisamos al usuario
        if (identidadActual.equals(identidadTabla) && 
            nombreActual.equals(nombreTabla) && 
            apellidoActual.equals(apellidoTabla) && 
            telefonoActual.equals(telefonoTabla) && 
            correoActual.equals(correoTabla)) {
            
            JOptionPane.showMessageDialog(this, "No se han detectado cambios en los datos.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return; // Salimos sin tocar la base de datos
        }

        // 4. Si pasó la comparación, procedemos con el UPDATE normal
        if (identidadActual.isEmpty() || nombreActual.isEmpty() || apellidoActual.isEmpty() || telefonoActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No deje campos obligatorios vacíos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        modelo.Cliente clienteModificado = new modelo.Cliente(idClienteSeleccionado, identidadActual, nombreActual, apellidoActual, telefonoActual, correoActual);
        dao.ClienteDAO dao = new dao.ClienteDAO();
        
        if (dao.actualizar(clienteModificado)) {
            JOptionPane.showMessageDialog(this, "¡Datos actualizados!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            btnLimpiarActionPerformed(evt); // Reutilizamos tu método de limpiar
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
            // 1. Validamos que haya alguien seleccionado (por si acaso)
        if (idClienteSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la tabla para eliminarlo.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Declaramos nuestro conductor UNA sola vez
        dao.ClienteDAO dao = new dao.ClienteDAO();

        // 3. EL CANDADO: Revisamos si tiene historial
        if (dao.tieneHistorial(idClienteSeleccionado)) {
            JOptionPane.showMessageDialog(this, 
                "No se puede eliminar este cliente porque tiene equipos o reparaciones en el historial.\nPor seguridad contable, sus datos están protegidos.", 
                "Acción Denegada", 
                JOptionPane.ERROR_MESSAGE);
            return; // Detenemos la eliminación
        }

        // 4. Pedimos confirmación al usuario (¡Regla de oro de UX!)
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar este cliente?\n(Sus datos serán anonimizados por seguridad del sistema)", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

        // 5. Si el usuario elige "Sí"
        if (confirmacion == JOptionPane.YES_OPTION) {

            // Usamos la misma variable "dao" que creamos arriba para eliminar
            if (dao.eliminar(idClienteSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Restauramos el formulario a su estado original
                txtIdentidad.setText("");
                txtNombre.setText("");
                txtApellido.setText("");
                txtTelefono.setText("");
                txtCorreo.setText("");
                txtCliente.setText(""); // Limpiamos el buscador por si había algo escrito

                // Reiniciamos la variable secreta
                idClienteSeleccionado = -1;

                // TRUCO DE UX: Regresamos los botones a la normalidad
                btnGuardar.setEnabled(true);
                btnModificar.setEnabled(false); // Apagamos Modificar
                btnEliminar.setEnabled(false);     // Apagamos Eliminar

                // Recargamos la tabla para que se vea la fila anonimizada al instante
                cargarTablaClientes(""); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // 1. Vaciamos todas las cajas de texto
        txtIdentidad.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtCliente.setText(""); // Vaciamos el buscador
        
        // 2. Olvidamos al cliente que estaba seleccionado
        idClienteSeleccionado = -1;
        
        // 3. Restauramos los botones a su estado inicial de "Registro Nuevo"
        btnGuardar.setEnabled(true);     // Encendemos Guardar
        btnModificar.setEnabled(false);  // Apagamos Modificar
        btnEliminar.setEnabled(false);      // Apagamos Eliminar
        
        // 4. Deseleccionamos cualquier fila que haya quedado marcada en la tabla visualmente
        tablaClientes.clearSelection();
        
        // 5. Recargamos la tabla por si acaso
        cargarTablaClientes("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    // ==============================================================
    // NUEVO DISEÑO MODERNO: PANEL DE CLIENTES
    // ==============================================================
    private void aplicarDisenoClientes() {
        // 1. Borramos el diseño oscuro viejo
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout(20, 20));
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        this.setBackground(new java.awt.Color(240, 244, 248)); // Fondo gris claro

        // 2. TÍTULO SUPERIOR
        javax.swing.JLabel lblTitulo = new javax.swing.JLabel("Gestión de Clientes");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 26));
        lblTitulo.setForeground(new java.awt.Color(44, 62, 80));
        this.add(lblTitulo, java.awt.BorderLayout.NORTH);

        // 3. ZONA IZQUIERDA: BUSCADOR Y TABLA
        javax.swing.JPanel panelIzquierdo = new javax.swing.JPanel(new java.awt.BorderLayout(0, 10));
        panelIzquierdo.setOpaque(false);
        
        // --- El Buscador ---
        javax.swing.JPanel panelBuscador = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
        panelBuscador.setOpaque(false);
        javax.swing.JLabel lblBuscar = new javax.swing.JLabel("Buscar Cliente (Nombre o Identidad):");
        lblBuscar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        txtCliente.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)); // Este es tu campo de búsqueda
        txtCliente.setPreferredSize(new java.awt.Dimension(0, 35));
        panelBuscador.add(lblBuscar, java.awt.BorderLayout.WEST);
        panelBuscador.add(txtCliente, java.awt.BorderLayout.CENTER);
        
        // --- La Tabla ---
        tablaClientes.setRowHeight(35);
        tablaClientes.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        tablaClientes.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        scrollBusqueda.getViewport().setBackground(java.awt.Color.WHITE);
        scrollBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        panelIzquierdo.add(panelBuscador, java.awt.BorderLayout.NORTH);
        panelIzquierdo.add(scrollBusqueda, java.awt.BorderLayout.CENTER);
        this.add(panelIzquierdo, java.awt.BorderLayout.CENTER); // El panel izquierdo toma todo el espacio central

        // 4. ZONA DERECHA: FORMULARIO BLANCO
        javax.swing.JPanel panelFormulario = new javax.swing.JPanel(new java.awt.GridBagLayout());
        panelFormulario.setBackground(java.awt.Color.WHITE);
        panelFormulario.setPreferredSize(new java.awt.Dimension(300, 0));
        panelFormulario.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)),
                javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gbc.insets = new java.awt.Insets(5, 0, 2, 0); // Márgenes más pequeños porque hay muchos campos
        gbc.weightx = 1.0;
        gbc.gridx = 0;

        javax.swing.JLabel lblSub = new javax.swing.JLabel("Datos del Cliente");
        lblSub.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
        lblSub.setForeground(java.awt.Color.GRAY);
        gbc.gridy = 0; gbc.insets = new java.awt.Insets(0, 0, 15, 0);
        panelFormulario.add(lblSub, gbc);

        // Agregamos tus campos generados por NetBeans al form
        gbc.insets = new java.awt.Insets(5, 0, 2, 0);
        gbc.gridy++; panelFormulario.add(new javax.swing.JLabel("Identidad:"), gbc);
        gbc.gridy++; panelFormulario.add(txtIdentidad, gbc);

        gbc.gridy++; panelFormulario.add(new javax.swing.JLabel("Nombre:"), gbc);
        gbc.gridy++; panelFormulario.add(txtNombre, gbc);

        gbc.gridy++; panelFormulario.add(new javax.swing.JLabel("Apellido:"), gbc);
        gbc.gridy++; panelFormulario.add(txtApellido, gbc);

        gbc.gridy++; panelFormulario.add(new javax.swing.JLabel("Teléfono:"), gbc);
        gbc.gridy++; panelFormulario.add(txtTelefono, gbc);

        gbc.gridy++; panelFormulario.add(new javax.swing.JLabel("Correo:"), gbc);
        gbc.gridy++; panelFormulario.add(txtCorreo, gbc);

        // Panel de Botones 2x2
        gbc.gridy++; gbc.insets = new java.awt.Insets(20, 0, 0, 0);
        javax.swing.JPanel panelBotones = new javax.swing.JPanel(new java.awt.GridLayout(2, 2, 10, 10));
        panelBotones.setOpaque(false);

        // Estilos y "Manitas" de los botones
        btnGuardar.setBackground(new java.awt.Color(46, 204, 113)); btnGuardar.setForeground(java.awt.Color.WHITE);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnModificar.setBackground(new java.awt.Color(52, 152, 219)); btnModificar.setForeground(java.awt.Color.WHITE);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEliminar.setBackground(new java.awt.Color(231, 76, 60)); btnEliminar.setForeground(java.awt.Color.WHITE);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLimpiar.setBackground(java.awt.Color.GRAY); btnLimpiar.setForeground(java.awt.Color.WHITE);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelBotones.add(btnGuardar);
        panelBotones.add(btnModificar);
        panelBotones.add(btnEliminar);
        panelBotones.add(btnLimpiar);

        gbc.gridy++; panelFormulario.add(panelBotones, gbc);

        // Empujamos todo hacia arriba para que no flote
        gbc.gridy++; gbc.weighty = 1.0;
        panelFormulario.add(javax.swing.Box.createVerticalGlue(), gbc);

        // Agregamos el formulario a la derecha de la pantalla
        this.add(panelFormulario, java.awt.BorderLayout.EAST);

        this.revalidate();
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollBusqueda;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
