
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Ever Chavez
 */
public class PanelListadoOrdenes extends javax.swing.JPanel {

    /**
     * Creates new form PanelListadoOrdenes
     */
    public PanelListadoOrdenes() {
        initComponents();
        cargarTablaGeneral();
    }
    
    // EL NUEVO MÉTODO PARA EL FILTRO
    // =========================================================================
    // 1. EL MÉTODO ORIGINAL (El que atiende al abrir la ventana y no pide texto)
    // =========================================================================
    public void cargarTablaGeneral() {
        dao.OrdenReparacionDAO dao = new dao.OrdenReparacionDAO();
        java.util.List<Object[]> lista = dao.listarReporteCompleto();
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("Cliente");
        modelo.addColumn("Equipo");
        modelo.addColumn("Problema");
        modelo.addColumn("Estado");
        modelo.addColumn("Costo");
        
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        
        tablaGeneral.setModel(modelo);
        tablaGeneral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaGeneral.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaGeneral.getColumnModel().getColumn(2).setPreferredWidth(120);
        tablaGeneral.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaGeneral.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaGeneral.getColumnModel().getColumn(5).setPreferredWidth(80);
    }

    // =========================================================================
    // 2. EL MÉTODO NUEVO (El que atiende al ComboBox y SÍ pide un texto de filtro)
    // =========================================================================
    public void cargarTablaGeneral(String estadoFiltro) {
        dao.OrdenReparacionDAO dao = new dao.OrdenReparacionDAO();
        java.util.List<Object[]> lista;
        
        // Evaluamos qué eligió el usuario en el ComboBox
        if (estadoFiltro.equals("Todos")) {
            lista = dao.listarReporteCompleto(); // Trae todo
        } else {
            lista = dao.filtrarPorEstado(estadoFiltro); // Trae solo el estado seleccionado
        }
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("N°");
        modelo.addColumn("Cliente");
        modelo.addColumn("Equipo");
        modelo.addColumn("Problema");
        modelo.addColumn("Estado");
        modelo.addColumn("Costo");
        
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        
        tablaGeneral.setModel(modelo);
        tablaGeneral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaGeneral.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaGeneral.getColumnModel().getColumn(2).setPreferredWidth(120);
        tablaGeneral.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaGeneral.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaGeneral.getColumnModel().getColumn(5).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelContenedor = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnActualizarOrden = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        scrollTablaGeneral = new javax.swing.JScrollPane();
        tablaGeneral = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtIdOrden = new javax.swing.JTextField();
        cmbNuevoEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCostoFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarOrden = new javax.swing.JTextField();
        btnEditarDetalles = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        cmbFiltroEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenedor.setBackground(new java.awt.Color(0, 0, 0));
        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panelContenedor.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 44));

        btnActualizarOrden.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnActualizarOrden.setText("Actualizar Orden");
        btnActualizarOrden.addActionListener(this::btnActualizarOrdenActionPerformed);
        panelContenedor.add(btnActualizarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, 90));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panelContenedor.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 44));

        tablaGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGeneralMouseClicked(evt);
            }
        });
        scrollTablaGeneral.setViewportView(tablaGeneral);

        panelContenedor.add(scrollTablaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 790, 310));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Orden");
        panelContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtIdOrden.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIdOrden.setEnabled(false);
        panelContenedor.add(txtIdOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        cmbNuevoEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbNuevoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Recibido", "En Revision", "Reparado", "Entregado", "Sin Reparacion" }));
        panelContenedor.add(cmbNuevoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 150, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Orden N°");
        panelContenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtCostoFinal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelContenedor.add(txtCostoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo Final");
        panelContenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txtBuscarOrden.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBuscarOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarOrdenKeyReleased(evt);
            }
        });
        panelContenedor.add(txtBuscarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 290, 30));

        btnEditarDetalles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditarDetalles.setText("Editar Detalles");
        btnEditarDetalles.addActionListener(this::btnEditarDetallesActionPerformed);
        panelContenedor.add(btnEditarDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 150, 40));

        btnEntregar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(this::btnEntregarActionPerformed);
        panelContenedor.add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, 44));

        cmbFiltroEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbFiltroEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Recibido", "En Reparacion", "Listo para Entrega", "Entregado" }));
        cmbFiltroEstado.addItemListener(this::cmbFiltroEstadoItemStateChanged);
        panelContenedor.add(cmbFiltroEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, 30));

        jPanel1.add(panelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaGeneralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGeneralMouseClicked
        int fila = tablaGeneral.getSelectedRow();
        
        if (fila >= 0) {
            // 1. ID de Orden (Columna 0)
            txtIdOrden.setText(tablaGeneral.getValueAt(fila, 0).toString());
            
            // 2. Estado (Columna 4)
            Object valorEstado = tablaGeneral.getValueAt(fila, 4);
            if (valorEstado != null) {
                cmbNuevoEstado.setSelectedItem(valorEstado.toString().trim());
            }
            
            // 3. Costo (Columna 5)
            Object valorCosto = tablaGeneral.getValueAt(fila, 5);
            txtCostoFinal.setText(valorCosto != null ? valorCosto.toString() : "0.0");
        }
    }//GEN-LAST:event_tablaGeneralMouseClicked

    private void btnActualizarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarOrdenActionPerformed
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden de la tabla.");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdOrden.getText());
            String estado = cmbNuevoEstado.getSelectedItem().toString();
            
            // Limpiamos el texto del costo por si tiene espacios
            String costoTexto = txtCostoFinal.getText().trim();
            double costo = Double.parseDouble(costoTexto);

            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
            if (daoOrden.actualizarEstadoYCosto(id, estado, costo)) {
                JOptionPane.showMessageDialog(this, "¡Orden actualizada correctamente!");
                cargarTablaGeneral(); 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un costo válido (ej: 150.00)");
        }
    }//GEN-LAST:event_btnActualizarOrdenActionPerformed

    private void txtBuscarOrdenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOrdenKeyReleased
        String texto = txtBuscarOrden.getText().trim();
        dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
        
        // Si está vacío, cargamos la tabla normal. Si tiene texto, usamos el buscador.
        java.util.List<Object[]> lista = texto.isEmpty() ? 
                                         daoOrden.listarReporteCompleto() : 
                                         daoOrden.buscarOrden(texto);
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("N° Orden");
        modelo.addColumn("Cliente");
        modelo.addColumn("Equipo");
        modelo.addColumn("Problema");
        modelo.addColumn("Estado");
        modelo.addColumn("Costo");
        
        for (Object[] fila : lista) {
            modelo.addRow(fila);
        }
        
        tablaGeneral.setModel(modelo);
        
        // Mantenemos los tamaños de las columnas para que no se desarmen
        tablaGeneral.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaGeneral.getColumnModel().getColumn(1).setPreferredWidth(150);
        tablaGeneral.getColumnModel().getColumn(2).setPreferredWidth(120);
        tablaGeneral.getColumnModel().getColumn(3).setPreferredWidth(250);
        tablaGeneral.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaGeneral.getColumnModel().getColumn(5).setPreferredWidth(80);
    }//GEN-LAST:event_txtBuscarOrdenKeyReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // 1. Validar que haya tocado una orden
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una orden de la tabla para eliminarla.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pedir confirmación (NUNCA borrar directo)
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar la Orden N° " + txtIdOrden.getText() + "?\nEsta acción no se puede deshacer.", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtIdOrden.getText());
            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
            
            if (daoOrden.eliminar(id)) {
                JOptionPane.showMessageDialog(this, "Orden eliminada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiamos los campos y refrescamos la tabla
                txtIdOrden.setText("");
                cmbNuevoEstado.setSelectedIndex(0);
                txtCostoFinal.setText("");
                cargarTablaGeneral(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la orden.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDetallesActionPerformed
        // 1. Validar que haya seleccionado una orden
        if (txtIdOrden.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione una orden de la tabla primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idOrden = Integer.parseInt(txtIdOrden.getText());
        dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
        
        // 2. Traer los datos actuales
        String[] textosActuales = daoOrden.obtenerTextosOrden(idOrden);
        String problemaActual = textosActuales[0] != null ? textosActuales[0] : "";
        String trabajoActual = textosActuales[1] != null ? textosActuales[1] : "";

        // 3. Crear los JTextArea por código
        javax.swing.JTextArea txtProblema = new javax.swing.JTextArea(5, 30);
        txtProblema.setText(problemaActual);
        txtProblema.setLineWrap(true);
        txtProblema.setWrapStyleWord(true);
        
        javax.swing.JTextArea txtTrabajo = new javax.swing.JTextArea(5, 30);
        txtTrabajo.setText(trabajoActual);
        txtTrabajo.setLineWrap(true);
        txtTrabajo.setWrapStyleWord(true);

        // 4. Armar el panel flotante
        javax.swing.JPanel panelEdicion = new javax.swing.JPanel(new java.awt.GridLayout(4, 1, 5, 5));
        panelEdicion.add(new javax.swing.JLabel("Problema Reportado:"));
        panelEdicion.add(new javax.swing.JScrollPane(txtProblema));
        panelEdicion.add(new javax.swing.JLabel("Trabajo Realizado:"));
        panelEdicion.add(new javax.swing.JScrollPane(txtTrabajo));

        // 5. Mostrar la ventana y esperar a que el usuario le dé a "Aceptar"
        int opcion = JOptionPane.showConfirmDialog(this, panelEdicion, "Editando Orden N° " + idOrden, 
                                                   JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        // 6. Si el usuario le dio a "OK", guardamos en la base de datos
        if (opcion == JOptionPane.OK_OPTION) {
            String nuevoProblema = txtProblema.getText().trim();
            String nuevoTrabajo = txtTrabajo.getText().trim();
            
            if (daoOrden.actualizarTextosOrden(idOrden, nuevoProblema, nuevoTrabajo)) {
                JOptionPane.showMessageDialog(this, "Detalles actualizados correctamente.");
                cargarTablaGeneral(); // Refrescar la tabla para ver el nuevo problema
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar los detalles.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarDetallesActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
       int fila = tablaGeneral.getSelectedRow(); 
        
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione una orden de la lista para entregar.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. Extraemos TODOS los datos necesarios de tu tabla
        String idOrden = tablaGeneral.getValueAt(fila, 0).toString();
        String cliente = tablaGeneral.getValueAt(fila, 1).toString();
        String equipo = tablaGeneral.getValueAt(fila, 2).toString();
        String problema = tablaGeneral.getValueAt(fila, 3).toString();
        String estadoActual = tablaGeneral.getValueAt(fila, 4).toString();
        String costoTotal = tablaGeneral.getValueAt(fila, 5).toString();

        if (estadoActual.equals("Entregado")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Este equipo ya fue entregado y cobrado anteriormente.", "Aviso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Confirmar la entrega del equipo y el cobro de L. " + costoTotal + "?\nSe generará el ticket de cobro automáticamente.",
                "Cobro de Reparación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                
            dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO(); 
            
            // Convertimos el ID a número para que la base de datos lo entienda
            if (daoOrden.marcarComoEntregado(Integer.parseInt(idOrden))) {
                
                // 2. ¡LA MAGIA DEL PDF! Llamamos a tu nueva clase
                utilidades.GeneradorPDF generador = new utilidades.GeneradorPDF();
                boolean ticketCreado = generador.crearTicket(idOrden, cliente, equipo, problema, costoTotal);
                
                if (ticketCreado) {
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Cobro exitoso!\nEl ticket PDF se ha generado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Por si la base de datos guarda, pero el PDF falla (ej. si el archivo estaba abierto)
                    javax.swing.JOptionPane.showMessageDialog(this, "Cobro registrado, pero hubo un error al crear el PDF.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                }

                // 3. Refrescamos la tabla para que el estado cambie visualmente
                // ¡Asegúrate de poner aquí tu método real para recargar la tabla!
                // cargarTabla(); 
                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la entrega en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void cmbFiltroEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFiltroEstadoItemStateChanged

        String estadoSeleccionado = cmbFiltroEstado.getSelectedItem().toString();
        // Llamas a tu método de llenar tabla pero pasándole el filtro
        cargarTablaGeneral(estadoSeleccionado);

    }//GEN-LAST:event_cmbFiltroEstadoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarOrden;
    private javax.swing.JButton btnEditarDetalles;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbFiltroEstado;
    private javax.swing.JComboBox<String> cmbNuevoEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JScrollPane scrollTablaGeneral;
    private javax.swing.JTable tablaGeneral;
    private javax.swing.JTextField txtBuscarOrden;
    private javax.swing.JTextField txtCostoFinal;
    private javax.swing.JTextField txtIdOrden;
    // End of variables declaration//GEN-END:variables
}
