package gui;

import javax.swing.JOptionPane;



public class PanelOrdenes extends javax.swing.JPanel {
    
    
    private int idEquipoSeleccionado = -1;
    
    public PanelOrdenes() {
        initComponents();
        scrollBusquedaEquipo.setVisible(false); // Ocultar la tabla al empezar
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollBusquedaEquipo = new javax.swing.JScrollPane();
        tablaBusquedaEquipo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarEquipo = new javax.swing.JTextField();
        panelTrabajo = new javax.swing.JScrollPane();
        txtTrabajo = new javax.swing.JTextArea();
        panelProblema = new javax.swing.JScrollPane();
        txtProblema = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtEquipo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaBusquedaEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaBusquedaEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusquedaEquipoMouseClicked(evt);
            }
        });
        scrollBusquedaEquipo.setViewportView(tablaBusquedaEquipo);

        jPanel1.add(scrollBusquedaEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 700, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREAR ORDEN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, 44));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtBuscarEquipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBuscarEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarEquipoKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 529, -1));

        txtTrabajo.setColumns(20);
        txtTrabajo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTrabajo.setRows(5);
        txtTrabajo.setText("Escribe aquí la reparación realizada.");
        txtTrabajo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTrabajoFocusLost(evt);
            }
        });
        txtTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTrabajoMouseClicked(evt);
            }
        });
        panelTrabajo.setViewportView(txtTrabajo);

        jPanel1.add(panelTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 700, 60));

        txtProblema.setColumns(20);
        txtProblema.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtProblema.setRows(5);
        txtProblema.setText("Escribe aquí el problema de tu equipo.");
        txtProblema.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProblemaFocusLost(evt);
            }
        });
        txtProblema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProblemaMouseClicked(evt);
            }
        });
        panelProblema.setViewportView(txtProblema);

        jPanel1.add(panelProblema, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 700, 60));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buscar Equipo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Recibido", "En Revision", "Reparado", "Entregado", "Sin Reparacion" }));
        cmbEstado.addActionListener(this::cmbEstadoActionPerformed);
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 120, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Equipo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        txtEquipo.setEditable(false);
        txtEquipo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEquipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEquipoKeyReleased(evt);
            }
        });
        jPanel1.add(txtEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, -1));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 290, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cliente:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 810, 490));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Background3.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // 1. Validar que seleccionó un equipo
        if (idEquipoSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo de la lista.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Capturar los datos de los campos
        String problema = txtProblema.getText().trim();
        String trabajo = txtTrabajo.getText().trim();
        String estado = cmbEstado.getSelectedItem().toString();
        
        // Validación de problema (no puede estar vacío)
        if (problema.isEmpty() || problema.equals("Escribe aquí el problema de tu equipo.")) {
            JOptionPane.showMessageDialog(this, "Por favor, describa el problema del equipo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // El costo lo podemos dejar en 0 por ahora o añadir un txtCosto si lo tienes
        double costo = 0.0; 

        // 3. Crear el objeto modelo (Asegúrate de tener este constructor en tu clase OrdenReparacion)
        modelo.OrdenReparacion nuevaOrden = new modelo.OrdenReparacion();
        nuevaOrden.setIdEquipo(idEquipoSeleccionado);
        nuevaOrden.setProblemaReportado(problema);
        nuevaOrden.setTrabajoRealizado(trabajo);
        nuevaOrden.setEstado(estado);
        nuevaOrden.setCosto(costo);

        // 4. Llamar al DAO para insertar
        dao.OrdenReparacionDAO daoOrden = new dao.OrdenReparacionDAO();
        
        if (daoOrden.insertar(nuevaOrden)) {
            JOptionPane.showMessageDialog(this, "¡Orden de reparación creada con éxito!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // 5. Limpiar el formulario
            txtBuscarEquipo.setText("");
            txtProblema.setText("");
            txtTrabajo.setText("");
            cmbEstado.setSelectedIndex(0);
            idEquipoSeleccionado = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la orden. Revise la conexión.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarEquipoKeyReleased
                                            
        String texto = txtBuscarEquipo.getText().trim();
        
        if (texto.isEmpty()) {
            scrollBusquedaEquipo.setVisible(false);
            txtNombre.setText(""); // Limpiamos la caja nueva
            txtEquipo.setText(""); // Limpiamos la caja nueva
            return;
        }

        // Llamamos al método que creamos en el DAO
        dao.EquipoRegistradoDAO daoEquipo = new dao.EquipoRegistradoDAO();
        java.util.List<Object[]> lista = daoEquipo.buscarEquipoCompleto(texto);

        // Modelo de tabla para mostrar: ID, Modelo, Serie, Dueño
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Modelo");
        modeloTabla.addColumn("Serie/IMEI");
        modeloTabla.addColumn("Dueño");

        for (Object[] fila : lista) {
            modeloTabla.addRow(fila);
        }

        tablaBusquedaEquipo.setModel(modeloTabla);

        // Mostrar u ocultar según resultados
        if (lista.size() > 0) {
            scrollBusquedaEquipo.setVisible(true);
        } else {
            scrollBusquedaEquipo.setVisible(false);
        }
    
    }//GEN-LAST:event_txtBuscarEquipoKeyReleased
  
    private void tablaBusquedaEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusquedaEquipoMouseClicked
        int fila = tablaBusquedaEquipo.getSelectedRow();
        
        if (fila >= 0) {
            try {
                // 1. ¡MANTENEMOS TU LÓGICA VITAL! Guardamos el ID en tu variable global
                String idStr = tablaBusquedaEquipo.getValueAt(fila, 0).toString();
                this.idEquipoSeleccionado = Integer.parseInt(idStr);
                
                // 2. Capturamos los datos de la tabla flotante
                String modelo = tablaBusquedaEquipo.getValueAt(fila, 1).toString();
                String dueno = tablaBusquedaEquipo.getValueAt(fila, 3).toString();
                
                // 3. Llenamos tus nuevas cajitas grises para que se vea súper Premium
                txtEquipo.setText(modelo);
                txtNombre.setText(dueno);
                
                // 5. Ocultamos la tabla flotante
                scrollBusquedaEquipo.setVisible(false);
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al seleccionar equipo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tablaBusquedaEquipoMouseClicked

    private void txtProblemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProblemaMouseClicked
        if (txtProblema.getText().equals("Escribe aquí el problema de tu equipo.")) {
            txtProblema.setText("");
        }
    }//GEN-LAST:event_txtProblemaMouseClicked

    private void txtTrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTrabajoMouseClicked
        // .trim() elimina espacios accidentales al inicio o final
        if(txtTrabajo.getText().trim().equals("Escribe aquí la reparación realizada.")) {
            txtTrabajo.setText("");
        }
    }//GEN-LAST:event_txtTrabajoMouseClicked

    private void txtTrabajoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTrabajoFocusLost
        if (txtTrabajo.getText().trim().isEmpty()) {
            txtTrabajo.setText("Escribe aquí la reparación realizada.");
        }
    }//GEN-LAST:event_txtTrabajoFocusLost

    private void txtProblemaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProblemaFocusLost
        // Si al salir, el cuadro está vacío, le devolvemos su mensaje guía
        if (txtProblema.getText().trim().isEmpty()) {
            txtProblema.setText("Escribe aquí el problema de tu equipo.");
        }
    }//GEN-LAST:event_txtProblemaFocusLost

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtEquipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEquipoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEquipoKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane panelProblema;
    private javax.swing.JScrollPane panelTrabajo;
    private javax.swing.JScrollPane scrollBusquedaEquipo;
    private javax.swing.JTable tablaBusquedaEquipo;
    private javax.swing.JTextField txtBuscarEquipo;
    private javax.swing.JTextField txtEquipo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtProblema;
    private javax.swing.JTextArea txtTrabajo;
    // End of variables declaration//GEN-END:variables
}
