
package gui;


public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar la ventana
        
        // 1. Apagamos todos los botones del menú lateral
        btnClientes.setEnabled(false);
        btnEquipos.setEnabled(false);
        btnOrden.setEnabled(false);
        btnListado.setEnabled(false);
        btnUsuarios.setEnabled(false);
        btnUsuarios.setVisible(false);
        btnEstadisticas.setEnabled(false);
        // (Agrega aquí cualquier otro botón de menú que tengas)

        // 2. Cargamos el PanelLogin por defecto en el centro
        PanelLogin login = new PanelLogin();
        mostrarPanel(login); // Usa el método que ya tienes para cambiar paneles
    }
    
    // Método público para que el PanelLogin pueda encender el sistema
    public void habilitarSistema(String rol) {
        // 1. Encendemos los botones generales que TODOS pueden usar
        btnClientes.setEnabled(true);
        btnEquipos.setEnabled(true);
        btnOrden.setEnabled(true); 
        btnListado.setEnabled(true);
        btnEstadisticas.setEnabled(true);
        
        // 2. ¡EL CANDADO DE ORO! 
        if (rol.equals("Administrador")) {
            // Si es el Jefe, encendemos y mostramos el botón secreto
            btnUsuarios.setEnabled(true);
            btnUsuarios.setVisible(true);
        } else {
            // Si es Técnico, nos aseguramos de que no lo vea
            btnUsuarios.setEnabled(false);
            btnUsuarios.setVisible(false);
        }
        
        // 3. Quitamos el login y ponemos tu pantalla de inicio por defecto
        gui.PanelClientes panelInicio = new gui.PanelClientes(); 
        mostrarPanel(panelInicio); 
    }
    
    private void mostrarPanel(javax.swing.JPanel p) {
        // Le damos el tamaño exacto del contenedor
        p.setSize(panelContenedor.getWidth(), panelContenedor.getHeight());
        p.setLocation(0,0);
        
        // Limpiamos el contenedor y le metemos el nuevo panel
        panelContenedor.removeAll();
        panelContenedor.add(p, java.awt.BorderLayout.CENTER);
        
        // Le decimos a Java que refresque la pantalla
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }
    // Este método recibe el botón que acabas de presionar y ajusta todos los demás
    private void seleccionarBotonMenu(javax.swing.JButton botonActivo) {
        // 1. Primero, DESBLOQUEAMOS todos los botones del menú para que se puedan volver a usar
        btnClientes.setEnabled(true);
        
        // Cuando crees los otros botones en tu diseño, solo quítales las barras (//)
        // btnEquipos.setEnabled(true); 
        // btnOrdenes.setEnabled(true);
        // btnInventario.setEnabled(true);

        // 2. Por último, BLOQUEAMOS únicamente el botón en el que estamos actualmente
        botonActivo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnOrden = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnClientes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);
        btnClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClientesKeyPressed(evt);
            }
        });

        btnEquipos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEquipos.setText("Equipos");
        btnEquipos.addActionListener(this::btnEquiposActionPerformed);
        btnEquipos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEquiposKeyPressed(evt);
            }
        });

        btnOrden.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnOrden.setText("Orden");
        btnOrden.addActionListener(this::btnOrdenActionPerformed);
        btnOrden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOrdenKeyPressed(evt);
            }
        });

        btnListado.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnListado.setText("Listado");
        btnListado.addActionListener(this::btnListadoActionPerformed);
        btnListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnListadoKeyPressed(evt);
            }
        });

        btnUsuarios.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(this::btnUsuariosActionPerformed);
        btnUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUsuariosKeyPressed(evt);
            }
        });

        btnEstadisticas.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.addActionListener(this::btnEstadisticasActionPerformed);
        btnEstadisticas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEstadisticasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEstadisticas)
                .addGap(18, 18, 18)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        panelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstadisticasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEstadisticasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticasKeyPressed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        PanelEstadisticas p1 = new PanelEstadisticas();

        mostrarPanel(p1);
        seleccionarBotonMenu(btnEstadisticas);
        btnClientes.setEnabled(true);
        btnEquipos.setEnabled(true);
        btnOrden.setEnabled(true);
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnUsuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUsuariosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosKeyPressed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        PanelUsuarios p1 = new PanelUsuarios();

        mostrarPanel(p1);
        seleccionarBotonMenu(btnUsuarios);
        btnClientes.setEnabled(true);
        btnEquipos.setEnabled(true);
        btnOrden.setEnabled(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnListadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListadoKeyPressed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        PanelListadoOrdenes p1 = new PanelListadoOrdenes();

        mostrarPanel(p1);
        seleccionarBotonMenu(btnListado);
        btnClientes.setEnabled(true);
        btnEquipos.setEnabled(true);
        btnOrden.setEnabled(true);
    }//GEN-LAST:event_btnListadoActionPerformed

    private void btnOrdenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOrdenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrdenKeyPressed

    private void btnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenActionPerformed
        PanelOrdenes p1 = new PanelOrdenes();

        mostrarPanel(p1);
        seleccionarBotonMenu(btnOrden);
        btnClientes.setEnabled(true);
        btnEquipos.setEnabled(true);
        btnListado.setEnabled(true);
    }//GEN-LAST:event_btnOrdenActionPerformed

    private void btnEquiposKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEquiposKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEquiposKeyPressed

    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed
        // Creamos una instancia del panel de clientes
        PanelEquipos p1 = new PanelEquipos();

        // Llamamos al metodo para que lo muestre
        mostrarPanel(p1);
        seleccionarBotonMenu(btnEquipos);
        btnClientes.setEnabled(true);
        btnOrden.setEnabled(true);
        btnListado.setEnabled(true);
    }//GEN-LAST:event_btnEquiposActionPerformed

    private void btnClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClientesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesKeyPressed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // Creamos una instancia del panel de clientes
        PanelClientes p1 = new PanelClientes();

        // Llamamos al metodo para que lo muestre
        mostrarPanel(p1);
        seleccionarBotonMenu(btnClientes);
        btnEquipos.setEnabled(true);
        btnOrden.setEnabled(true);
        btnListado.setEnabled(true);

    }//GEN-LAST:event_btnClientesActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEquipos;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnOrden;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
    
}
